# This workflow uses actions that are not certified by GitHub. They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ] # Jos repositoriosi p채채haara ei ole main, muuta n채m채
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Regenerate binstubs for Linux
        run: bundle exec rails app:update:bin

      - name: Set executable permissions for bin/rails
        run: chmod +x bin/rails

      - name: Set up database
        run: |
          bin/rails db:create db:migrate RAILS_ENV=test
      - name: Run tests
        run: bundle exec rspec
      - name: Run RuboCop
        run: bundle exec rubocop --parallel
